## Update and Standardize cToken Implementation

_Updated as of block [14731801](https://etherscan.io/block/14731801) at 5/7/2022, 4:02:39 PM ET_

- ID: 49
- Proposer: [0x8169522c2C57883E8EF80C498aAB7820dA539806](https://etherscan.io/address/0x8169522c2C57883E8EF80C498aAB7820dA539806)
- Start Block: 12687553 (6/22/2021, 9:36:06 PM ET)
- End Block: 12707263 (6/25/2021, 11:31:43 PM ET)
- Targets: [0x70e36f6BF80a52b3B46b3aF8e106CC0ed743E8e4](https://etherscan.io/address/0x70e36f6BF80a52b3B46b3aF8e106CC0ed743E8e4#code); [0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643](https://etherscan.io/address/0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643#code); [0xFAce851a4921ce59e912d19329929CE6da6EB0c7](https://etherscan.io/address/0xFAce851a4921ce59e912d19329929CE6da6EB0c7#code); [0x12392F67bdf24faE0AF363c24aC620a2f67DAd86](https://etherscan.io/address/0x12392F67bdf24faE0AF363c24aC620a2f67DAd86#code); [0x35A18000230DA775CAc24873d00Ff85BccdeD550](https://etherscan.io/address/0x35A18000230DA775CAc24873d00Ff85BccdeD550#code); [0xf650C3d88D12dB855b8bf7D11Be6C55A4e07dCC9](https://etherscan.io/address/0xf650C3d88D12dB855b8bf7D11Be6C55A4e07dCC9#code); [0xccF4429DB6322D5C611ee964527D42E5d685DD6a](https://etherscan.io/address/0xccF4429DB6322D5C611ee964527D42E5d685DD6a#code); [0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B](https://etherscan.io/address/0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B#code)

<details>
  <summary>Proposal text</summary>

> # Update and Standardize cToken Implementation
> This proposal is a patch, developed by Compound Labs, which updates the base cToken implementation contract, and adopts it across all upgradable markets.
> 
> ### Changelog
> The `seize` function has been modified to transfer 2.8% of a liquidation to cToken reserves, reducing the risk of cascading liquidations that could render the protocol insolvent. With each liquidation, the protocol’s ability to recover (or utilize reserves) increases.
> 
> Given the proliferation of COMP-like governance tokens, the `delegate` function has been merged into the base cToken implementation.
> 
> ### Adoption
> The seven upgradable cTokens, deployed starting 18 months ago, currently rely on five different cToken implementation contracts, many of which lack the most modern features.
> 
> This proposal unifies all upgradable cTokens with a single implementation, which reduces the surface area of technical debt, and slightly reduces gas costs.
> 
> ### Development
> This patch was developed publicly, coupled with completed scenario analysis. In addition to the Compound Labs bug bounty program, a secondary bug bounty was offered through [Immunefi](https://immunefi.com/bounty/compound/).
> 
> During the review period for [Proposal 048](https://compound.finance/governance/proposals/48), community member pyggie identified potential improvements to the cToken event logs and public interface; these have been included in this proposal, alongside a bounty of 30 COMP for their efforts.
> 
> [Discussion](https://www.comp.xyz/t/safety-and-gas-patches/1723)
</details>

### Checks
#### Reports all state changes from the proposal ✅ Passed
  




Info:
- State changes:
    - CErc20Delegator (Compound Collateral) at `0x70e36f6BF80a52b3B46b3aF8e106CC0ed743E8e4`
        - `implementation` changed from `0x338f7e5d19d9953b76dd81446b142c2d9fe03482` to `0xa035b9e130f2b1aedc733eefb1c67ba4c503491f`
    - CErc20Delegator (Compound Wrapped BTC) at `0xccF4429DB6322D5C611ee964527D42E5d685DD6a`
        - `implementation` changed from `0x24aa720906378bb8364228bddb8cabbc1f6fe1ba` to `0xa035b9e130f2b1aedc733eefb1c67ba4c503491f`
    - Comp (Compound) at `0xc00e94Cb662C3520282E6f5717214004A7f26888`
        - `balances` key `0x3d9819210a31b4961b30ef54be2aed79b9c9cd3b` changed from `"272728344150032347136455"` to `"272698344150032347136455"`
        - `balances` key `0x91400be76b7171cf932ae252390d2b60e2c73013` changed from `"0"` to `"30000000000000000000"`
    - CErc20Delegator (Compound USDT) at `0xf650C3d88D12dB855b8bf7D11Be6C55A4e07dCC9`
        - `implementation` changed from `0x976aa93ca5aaa569109f4267589c619a097f001d` to `0xa035b9e130f2b1aedc733eefb1c67ba4c503491f`
    - CErc20Delegator (Compound Uniswap) at `0x35A18000230DA775CAc24873d00Ff85BccdeD550`
        - `implementation` changed from `0xa1849880593e96d2f7df77d0d38a7f2372ae10e0` to `0xa035b9e130f2b1aedc733eefb1c67ba4c503491f`
    - CErc20Delegator (Compound ChainLink Token) at `0xFAce851a4921ce59e912d19329929CE6da6EB0c7`
        - `implementation` changed from `0x24aa720906378bb8364228bddb8cabbc1f6fe1ba` to `0xa035b9e130f2b1aedc733eefb1c67ba4c503491f`
    - CErc20Delegator (Compound TrueUSD) at `0x12392F67bdf24faE0AF363c24aC620a2f67DAd86`
        - `implementation` changed from `0xce526fa199d2f772abbc5b40b3284cdab1b8e6de` to `0xa035b9e130f2b1aedc733eefb1c67ba4c503491f`
    - CErc20Delegator (Compound Dai) at `0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643`
        - `implementation` changed from `0x976aa93ca5aaa569109f4267589c619a097f001d` to `0xa035b9e130f2b1aedc733eefb1c67ba4c503491f`

#### Decodes target calldata into a human-readable format ✅ Passed
  




Info:
- On contract `0x70e36f6BF80a52b3B46b3aF8e106CC0ed743E8e4`, call `_setImplementation(address implementation_, bool allowResign, bytes becomeImplementationData)()` with arguments `implementation_=0xa035b9e130f2b1aedc733eefb1c67ba4c503491f`, `allowResign=true`, `becomeImplementationData=0x` (generic)
- On contract `0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643`, call `_setImplementation(address implementation_, bool allowResign, bytes becomeImplementationData)()` with arguments `implementation_=0xa035b9e130f2b1aedc733eefb1c67ba4c503491f`, `allowResign=true`, `becomeImplementationData=0x` (generic)
- On contract `0xFAce851a4921ce59e912d19329929CE6da6EB0c7`, call `_setImplementation(address implementation_, bool allowResign, bytes becomeImplementationData)()` with arguments `implementation_=0xa035b9e130f2b1aedc733eefb1c67ba4c503491f`, `allowResign=true`, `becomeImplementationData=0x` (generic)
- On contract `0x12392F67bdf24faE0AF363c24aC620a2f67DAd86`, call `_setImplementation(address implementation_, bool allowResign, bytes becomeImplementationData)()` with arguments `implementation_=0xa035b9e130f2b1aedc733eefb1c67ba4c503491f`, `allowResign=true`, `becomeImplementationData=0x` (generic)
- On contract `0x35A18000230DA775CAc24873d00Ff85BccdeD550`, call `_setImplementation(address implementation_, bool allowResign, bytes becomeImplementationData)()` with arguments `implementation_=0xa035b9e130f2b1aedc733eefb1c67ba4c503491f`, `allowResign=true`, `becomeImplementationData=0x` (generic)
- On contract `0xf650C3d88D12dB855b8bf7D11Be6C55A4e07dCC9`, call `_setImplementation(address implementation_, bool allowResign, bytes becomeImplementationData)()` with arguments `implementation_=0xa035b9e130f2b1aedc733eefb1c67ba4c503491f`, `allowResign=true`, `becomeImplementationData=0x` (generic)
- On contract `0xccF4429DB6322D5C611ee964527D42E5d685DD6a`, call `_setImplementation(address implementation_, bool allowResign, bytes becomeImplementationData)()` with arguments `implementation_=0xa035b9e130f2b1aedc733eefb1c67ba4c503491f`, `allowResign=true`, `becomeImplementationData=0x` (generic)
- On contract `0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B`, call `_grantComp(address recipient, uint256 amount)()` with arguments `recipient=0x91400be76b7171cf932ae252390d2b60e2c73013`, `amount=30000000000000000000` (generic)

#### Reports all events emitted from the proposal ✅ Passed
  




Info:
- Events Emitted:
    - CErc20Delegator (Compound Collateral) at `0x70e36f6BF80a52b3B46b3aF8e106CC0ed743E8e4`
        - `NewImplementation(oldImplementation: 0x338f7e5d19d9953b76dd81446b142c2d9fe03482, newImplementation: 0xa035b9e130f2b1aedc733eefb1c67ba4c503491f)`
    - CErc20Delegator (Compound Dai) at `0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643`
        - `NewImplementation(oldImplementation: 0x976aa93ca5aaa569109f4267589c619a097f001d, newImplementation: 0xa035b9e130f2b1aedc733eefb1c67ba4c503491f)`
    - CErc20Delegator (Compound ChainLink Token) at `0xFAce851a4921ce59e912d19329929CE6da6EB0c7`
        - `NewImplementation(oldImplementation: 0x24aa720906378bb8364228bddb8cabbc1f6fe1ba, newImplementation: 0xa035b9e130f2b1aedc733eefb1c67ba4c503491f)`
    - CErc20Delegator (Compound TrueUSD) at `0x12392F67bdf24faE0AF363c24aC620a2f67DAd86`
        - `NewImplementation(oldImplementation: 0xce526fa199d2f772abbc5b40b3284cdab1b8e6de, newImplementation: 0xa035b9e130f2b1aedc733eefb1c67ba4c503491f)`
    - CErc20Delegator (Compound Uniswap) at `0x35A18000230DA775CAc24873d00Ff85BccdeD550`
        - `NewImplementation(oldImplementation: 0xa1849880593e96d2f7df77d0d38a7f2372ae10e0, newImplementation: 0xa035b9e130f2b1aedc733eefb1c67ba4c503491f)`
    - CErc20Delegator (Compound USDT) at `0xf650C3d88D12dB855b8bf7D11Be6C55A4e07dCC9`
        - `NewImplementation(oldImplementation: 0x976aa93ca5aaa569109f4267589c619a097f001d, newImplementation: 0xa035b9e130f2b1aedc733eefb1c67ba4c503491f)`
    - CErc20Delegator (Compound Wrapped BTC) at `0xccF4429DB6322D5C611ee964527D42E5d685DD6a`
        - `NewImplementation(oldImplementation: 0x24aa720906378bb8364228bddb8cabbc1f6fe1ba, newImplementation: 0xa035b9e130f2b1aedc733eefb1c67ba4c503491f)`
    - Comp (Compound) at `0xc00e94Cb662C3520282E6f5717214004A7f26888`
        - `Transfer(from: 0x3d9819210a31b4961b30ef54be2aed79b9c9cd3b, to: 0x91400be76b7171cf932ae252390d2b60e2c73013, amount: 30000000000000000000)`
    - Unitroller at `0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B`
        - `CompGranted(recipient: 0x91400be76b7171cf932ae252390d2b60e2c73013, amount: 30000000000000000000)`

#### Check all targets are verified on Etherscan ✅ Passed
  




Info:
- Targets:
    - 0x70e36f6BF80a52b3B46b3aF8e106CC0ed743E8e4: Contract (verified)
    - 0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643: Contract (verified)
    - 0xFAce851a4921ce59e912d19329929CE6da6EB0c7: Contract (verified)
    - 0x12392F67bdf24faE0AF363c24aC620a2f67DAd86: Contract (verified)
    - 0x35A18000230DA775CAc24873d00Ff85BccdeD550: Contract (verified)
    - 0xf650C3d88D12dB855b8bf7D11Be6C55A4e07dCC9: Contract (verified)
    - 0xccF4429DB6322D5C611ee964527D42E5d685DD6a: Contract (verified)
    - 0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B: Contract (verified)

#### Check all touched contracts are verified on Etherscan ✅ Passed
  




Info:
- Touched address:
    - 0x88FB3D509fC49B515BFEb04e23f53ba339563981: EOA (verification not applicable)
    - 0xc0Da02939E1441F497fd74F78cE7Decb17B66529: Contract (verified)
    - 0xAAAaaAAAaaaa8FdB04F544F4EEe52939CddCe378: Contract (verified)
    - 0x6d903f6003cca6255D85CcA4D3B5E5146dC33925: Contract (verified)
    - 0x70e36f6BF80a52b3B46b3aF8e106CC0ed743E8e4: Contract (verified)
    - 0x338f7e5d19d9953b76dD81446B142C2D9fE03482: Contract (verified)
    - 0xa035b9e130F2B1AedC733eEFb1C67Ba4c503491F: Contract (verified)
    - 0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643: Contract (verified)
    - 0x976aa93ca5Aaa569109f4267589c619a097f001D: Contract (verified)
    - 0xFAce851a4921ce59e912d19329929CE6da6EB0c7: Contract (verified)
    - 0x24aA720906378bb8364228Bddb8CAbbc1f6Fe1ba: Contract (verified)
    - 0x12392F67bdf24faE0AF363c24aC620a2f67DAd86: Contract (verified)
    - 0xcE526fA199d2f772ABBC5b40B3284cdAB1b8E6DE: Contract (verified)
    - 0x35A18000230DA775CAc24873d00Ff85BccdeD550: Contract (verified)
    - 0xa1849880593E96d2f7dF77D0D38a7f2372aE10E0: Contract (verified)
    - 0xf650C3d88D12dB855b8bf7D11Be6C55A4e07dCC9: Contract (verified)
    - 0xccF4429DB6322D5C611ee964527D42E5d685DD6a: Contract (verified)
    - 0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B: Contract (verified)
    - 0xbe7616B06f71e363A310Aa8CE8aD99654401ead7: Contract (verified)
    - 0xc00e94Cb662C3520282E6f5717214004A7f26888: Contract (verified)

#### Runs solc against the verified contracts ✅ Passed
  




Info:
- Compiler warnings for CErc20Delegate at `0x24aA720906378bb8364228Bddb8CAbbc1f6Fe1ba`

<details>
<summary>View warnings for CErc20Delegate at `0x24aA720906378bb8364228Bddb8CAbbc1f6Fe1ba`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>


- Compiler warnings for CCompLikeDelegate at `0x338f7e5d19d9953b76dD81446B142C2D9fE03482`

<details>
<summary>View warnings for CCompLikeDelegate at `0x338f7e5d19d9953b76dD81446B142C2D9fE03482`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>


- Compiler warnings for CErc20Delegator (Compound Uniswap) at `0x35A18000230DA775CAc24873d00Ff85BccdeD550`

<details>
<summary>View warnings for CErc20Delegator (Compound Uniswap) at `0x35A18000230DA775CAc24873d00Ff85BccdeD550`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>


- Compiler warnings for CErc20Delegator (Compound Dai) at `0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643`

<details>
<summary>View warnings for CErc20Delegator (Compound Dai) at `0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>


- Compiler warnings for CErc20Delegator (Compound Collateral) at `0x70e36f6BF80a52b3B46b3aF8e106CC0ed743E8e4`

<details>
<summary>View warnings for CErc20Delegator (Compound Collateral) at `0x70e36f6BF80a52b3B46b3aF8e106CC0ed743E8e4`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>


- Compiler warnings for CErc20Delegate at `0x976aa93ca5Aaa569109f4267589c619a097f001D`

<details>
<summary>View warnings for CErc20Delegate at `0x976aa93ca5Aaa569109f4267589c619a097f001D`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>


- Compiler warnings for CErc20Delegate at `0xa035b9e130F2B1AedC733eEFb1C67Ba4c503491F`

<details>
<summary>View warnings for CErc20Delegate at `0xa035b9e130F2B1AedC733eEFb1C67Ba4c503491F`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>


- Compiler warnings for CCompLikeDelegate at `0xa1849880593E96d2f7dF77D0D38a7f2372aE10E0`

<details>
<summary>View warnings for CCompLikeDelegate at `0xa1849880593E96d2f7dF77D0D38a7f2372aE10E0`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>


- Compiler warnings for Comp (Compound) at `0xc00e94Cb662C3520282E6f5717214004A7f26888`

<details>
<summary>View warnings for Comp (Compound) at `0xc00e94Cb662C3520282E6f5717214004A7f26888`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>


- Compiler warnings for CErc20Delegator (Compound Wrapped BTC) at `0xccF4429DB6322D5C611ee964527D42E5d685DD6a`

<details>
<summary>View warnings for CErc20Delegator (Compound Wrapped BTC) at `0xccF4429DB6322D5C611ee964527D42E5d685DD6a`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>


- Compiler warnings for CErc20Delegator (Compound USDT) at `0xf650C3d88D12dB855b8bf7D11Be6C55A4e07dCC9`

<details>
<summary>View warnings for CErc20Delegator (Compound USDT) at `0xf650C3d88D12dB855b8bf7D11Be6C55A4e07dCC9`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>


- Compiler warnings for CErc20Delegator (Compound ChainLink Token) at `0xFAce851a4921ce59e912d19329929CE6da6EB0c7`

<details>
<summary>View warnings for CErc20Delegator (Compound ChainLink Token) at `0xFAce851a4921ce59e912d19329929CE6da6EB0c7`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>


- Compiler warnings for CErc20Delegator (Compound TrueUSD) at `0x12392F67bdf24faE0AF363c24aC620a2f67DAd86`

<details>
<summary>View warnings for CErc20Delegator (Compound TrueUSD) at `0x12392F67bdf24faE0AF363c24aC620a2f67DAd86`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>


- Compiler warnings for CErc20Delegate at `0xcE526fA199d2f772ABBC5b40B3284cdAB1b8E6DE`

<details>
<summary>View warnings for CErc20Delegate at `0xcE526fA199d2f772ABBC5b40B3284cdAB1b8E6DE`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>


- Compiler warnings for Unitroller at `0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B`

<details>
<summary>View warnings for Unitroller at `0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>


- Compiler warnings for Comptroller at `0xbe7616B06f71e363A310Aa8CE8aD99654401ead7`

<details>
<summary>View warnings for Comptroller at `0xbe7616B06f71e363A310Aa8CE8aD99654401ead7`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>



#### Runs slither against the verified contracts ✅ Passed
  




Info:
- Slither report for CErc20Delegate at `0x24aA720906378bb8364228Bddb8CAbbc1f6Fe1ba`

<details>
<summary>View report for CErc20Delegate at `0x24aA720906378bb8364228Bddb8CAbbc1f6Fe1ba`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0x24aA720906378bb8364228Bddb8CAbbc1f6Fe1ba
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


- Slither report for CCompLikeDelegate at `0x338f7e5d19d9953b76dD81446B142C2D9fE03482`

<details>
<summary>View report for CCompLikeDelegate at `0x338f7e5d19d9953b76dD81446B142C2D9fE03482`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0x338f7e5d19d9953b76dD81446B142C2D9fE03482
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


- Slither report for CErc20Delegator (Compound Uniswap) at `0x35A18000230DA775CAc24873d00Ff85BccdeD550`

<details>
<summary>View report for CErc20Delegator (Compound Uniswap) at `0x35A18000230DA775CAc24873d00Ff85BccdeD550`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0x35A18000230DA775CAc24873d00Ff85BccdeD550
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


- Slither report for CErc20Delegator (Compound Dai) at `0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643`

<details>
<summary>View report for CErc20Delegator (Compound Dai) at `0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


- Slither report for CErc20Delegator (Compound Collateral) at `0x70e36f6BF80a52b3B46b3aF8e106CC0ed743E8e4`

<details>
<summary>View report for CErc20Delegator (Compound Collateral) at `0x70e36f6BF80a52b3B46b3aF8e106CC0ed743E8e4`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0x70e36f6BF80a52b3B46b3aF8e106CC0ed743E8e4
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


- Slither report for CErc20Delegate at `0x976aa93ca5Aaa569109f4267589c619a097f001D`

<details>
<summary>View report for CErc20Delegate at `0x976aa93ca5Aaa569109f4267589c619a097f001D`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0x976aa93ca5Aaa569109f4267589c619a097f001D
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


- Slither report for CErc20Delegate at `0xa035b9e130F2B1AedC733eEFb1C67Ba4c503491F`

<details>
<summary>View report for CErc20Delegate at `0xa035b9e130F2B1AedC733eEFb1C67Ba4c503491F`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0xa035b9e130F2B1AedC733eEFb1C67Ba4c503491F
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


- Slither report for CCompLikeDelegate at `0xa1849880593E96d2f7dF77D0D38a7f2372aE10E0`

<details>
<summary>View report for CCompLikeDelegate at `0xa1849880593E96d2f7dF77D0D38a7f2372aE10E0`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0xa1849880593E96d2f7dF77D0D38a7f2372aE10E0
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


- Slither report for Comp (Compound) at `0xc00e94Cb662C3520282E6f5717214004A7f26888`

<details>
<summary>View report for Comp (Compound) at `0xc00e94Cb662C3520282E6f5717214004A7f26888`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0xc00e94Cb662C3520282E6f5717214004A7f26888
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


- Slither report for CErc20Delegator (Compound Wrapped BTC) at `0xccF4429DB6322D5C611ee964527D42E5d685DD6a`

<details>
<summary>View report for CErc20Delegator (Compound Wrapped BTC) at `0xccF4429DB6322D5C611ee964527D42E5d685DD6a`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0xccF4429DB6322D5C611ee964527D42E5d685DD6a
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


- Slither report for CErc20Delegator (Compound USDT) at `0xf650C3d88D12dB855b8bf7D11Be6C55A4e07dCC9`

<details>
<summary>View report for CErc20Delegator (Compound USDT) at `0xf650C3d88D12dB855b8bf7D11Be6C55A4e07dCC9`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0xf650C3d88D12dB855b8bf7D11Be6C55A4e07dCC9
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


- Slither report for CErc20Delegator (Compound ChainLink Token) at `0xFAce851a4921ce59e912d19329929CE6da6EB0c7`

<details>
<summary>View report for CErc20Delegator (Compound ChainLink Token) at `0xFAce851a4921ce59e912d19329929CE6da6EB0c7`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0xFAce851a4921ce59e912d19329929CE6da6EB0c7
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


- Slither report for CErc20Delegator (Compound TrueUSD) at `0x12392F67bdf24faE0AF363c24aC620a2f67DAd86`

<details>
<summary>View report for CErc20Delegator (Compound TrueUSD) at `0x12392F67bdf24faE0AF363c24aC620a2f67DAd86`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0x12392F67bdf24faE0AF363c24aC620a2f67DAd86
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


- Slither report for CErc20Delegate at `0xcE526fA199d2f772ABBC5b40B3284cdAB1b8E6DE`

<details>
<summary>View report for CErc20Delegate at `0xcE526fA199d2f772ABBC5b40B3284cdAB1b8E6DE`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0xcE526fA199d2f772ABBC5b40B3284cdAB1b8E6DE
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


- Slither report for Unitroller at `0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B`

<details>
<summary>View report for Unitroller at `0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


- Slither report for Comptroller at `0xbe7616B06f71e363A310Aa8CE8aD99654401ead7`

<details>
<summary>View report for Comptroller at `0xbe7616B06f71e363A310Aa8CE8aD99654401ead7`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0xbe7616B06f71e363A310Aa8CE8aD99654401ead7
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


