## Dynamic Risk Parameters - Quarterly Update

_Updated as of block [14704537](https://etherscan.io/block/14704537) at 5/3/2022, 8:04:02 AM ET_

- ID: 82
- Proposer: [0x683a4F9915D6216f73d6Df50151725036bD26C02](https://etherscan.io/address/0x683a4F9915D6216f73d6Df50151725036bD26C02)
- Start Block: 14037258 (1/19/2022, 12:16:55 PM ET)
- End Block: 14056968 (1/22/2022, 1:15:11 PM ET)
- Targets: [0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B](https://etherscan.io/address/0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B#code); [0xc00e94Cb662C3520282E6f5717214004A7f26888](https://etherscan.io/address/0xc00e94Cb662C3520282E6f5717214004A7f26888#code); [0xCD18eAa163733Da39c232722cBC4E8940b1D8888](https://etherscan.io/address/0xCD18eAa163733Da39c232722cBC4E8940b1D8888#code)

<details>
  <summary>Proposal text</summary>

> # Dynamic Risk Parameters - Quarterly Update
> ## Background
> 
> Over the past several months, Gauntlet has been executing on its [Dynamic Risk Parameters](https://www.comp.xyz/t/dynamic-risk-parameters/2223/1) engagement to continuously optimize capital efficiency and mitigate depositor losses. In just a quarter, Gauntlet has launched the [Risk Dashboard](https://gov.gauntlet.network/compound), implemented 5 sets of parameter recommendations, published 2 monthly risk reviews, and safely unlocked  additional borrow for Compound while maintaining protocol risk at safe levels. 
> 
> ## Replacing Existing Contributor Grant with Sablier Stream
> 
> As outlined in the original proposal, at the start of every quarter Gauntlet will create a proposal to update the service fee payment (higher or lower) in accordance with the formula outlined in the [proposal](https://www.comp.xyz/t/dynamic-risk-parameters/2223#:~:text=parameter%20recommendations%20suggested.-,Cost,-Gauntlet%20charges%20a).
> 
> As it is the beginning of a new quarter, Gauntlet is updating its streaming grant. In addition, as was requested by the [Compound community](https://www.comp.xyz/t/migrate-gfx-labs-and-gauntlet-comp-streams-over-to-sablier/2785), Gauntlet will replace its existing COMP stream with a Sablier stream. This governance proposal sets the Contributor Comp Speed to Gauntlet to zero and sets up a Sablier stream to Gauntlet instead.
> 
> References:
> [Full proposal and forum discussion](https://www.comp.xyz/t/gauntlet-quarterly-contributorcompspeed-update/2829)
</details>

### Checks
#### Reports all state changes from the proposal ✅ Passed
  




Info:
- State changes:
    - Unitroller at `0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B`
        - Slot `0x025a5484c00b806368e0f6ad991aa6f49a3d2579fd87f611a4b249bb02e2d16f` changed from `"0x0000000000000000000000000000000000000000000000000000000000d439f1"` to `"0x0000000000000000000000000000000000000000000000000000000000000000"`
        - Slot `0x36f96ab7fa418365c13c43dd86d287faeba2c649b54976646be37243425ec701` changed from `"0x00000000000000000000000000000000000000000000000000171499d18b52d9"` to `"0x0000000000000000000000000000000000000000000000000000000000000000"`
        - Slot `0xc1e302cd4d20f064dc9d2c59d6c352a6aed36fc77cb3c17a6c4b65d85b81a363` changed from `"0x0000000000000000000000000000000000000000000000000000000000000000"` to `"0x000000000000000000000000000000000000000000000039dae6b66f01f2ec6d"`
    - Sablier at `0xCD18eAa163733Da39c232722cBC4E8940b1D8888`
        - `nextStreamId` changed from `102428` to `102429`
        - `streams` key `"102428"` changed from `{"deposit":"0","ratePerSecond":"0","remainingBalance":"0","startTime":"0","stopTime":"0","recipient":"0x0000000000000000000000000000000000000000","sender":"0x0000000000000000000000000000000000000000","tokenAddress":"0x0000000000000000000000000000000000000000"}` to `{"deposit":"21213001006232907484467","ratePerSecond":"1006232923497267","remainingBalance":"21213001006232907484467","startTime":"1643184000","stopTime":"1664265601","recipient":"0xd20c9667bf0047f313228f9fe11f8b9f8dc29bba","sender":"0x6d903f6003cca6255d85cca4d3b5e5146dc33925","tokenAddress":"0xc00e94cb662c3520282e6f5717214004a7f26888"}`
        - Slot `0x9745460fc7cde548d9401a311f1f9e3dd46ed14aad2dd84ddec96301bb2077d6` changed from `"0x0000000000000000000000000000000000000000000000000000000000000000"` to `"0x0000000000000000000000006d903f6003cca6255d85cca4d3b5e5146dc33925"`
        - Slot `0x9745460fc7cde548d9401a311f1f9e3dd46ed14aad2dd84ddec96301bb2077d7` changed from `"0x0000000000000000000000000000000000000000000000000000000000000000"` to `"0x000000000000000000000001c00e94cb662c3520282e6f5717214004a7f26888"`
        - Slot `0x9745460fc7cde548d9401a311f1f9e3dd46ed14aad2dd84ddec96301bb2077d1` changed from `"0x0000000000000000000000000000000000000000000000000000000000000000"` to `"0x00000000000000000000000000000000000000000000000000039329dbf76333"`
        - Slot `0x9745460fc7cde548d9401a311f1f9e3dd46ed14aad2dd84ddec96301bb2077d2` changed from `"0x0000000000000000000000000000000000000000000000000000000000000000"` to `"0x00000000000000000000000000000000000000000000047df586d7df64570d33"`
        - Slot `0x9745460fc7cde548d9401a311f1f9e3dd46ed14aad2dd84ddec96301bb2077d3` changed from `"0x0000000000000000000000000000000000000000000000000000000000000000"` to `"0x0000000000000000000000000000000000000000000000000000000061f0ff80"`
        - Slot `0x9745460fc7cde548d9401a311f1f9e3dd46ed14aad2dd84ddec96301bb2077d4` changed from `"0x0000000000000000000000000000000000000000000000000000000000000000"` to `"0x000000000000000000000000000000000000000000000000000000006332ad81"`
        - Slot `0x9745460fc7cde548d9401a311f1f9e3dd46ed14aad2dd84ddec96301bb2077d5` changed from `"0x0000000000000000000000000000000000000000000000000000000000000000"` to `"0x000000000000000000000000d20c9667bf0047f313228f9fe11f8b9f8dc29bba"`
    - Comp (Compound) at `0xc00e94Cb662C3520282E6f5717214004A7f26888`
        - `balances` key `0x6d903f6003cca6255d85cca4d3b5e5146dc33925` changed from `"277477831395009867815813"` to `"256264830388776960331346"`
        - `balances` key `0xcd18eaa163733da39c232722cbc4e8940b1d8888` changed from `"9999999999997200"` to `"21213011006232907481667"`

#### Decodes target calldata into a human-readable format ✅ Passed
  




Info:
- On contract `0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B`, call `_setContributorCompSpeed(address contributor, uint256 compSpeed)()` with arguments `contributor=0xd20c9667bf0047f313228f9fe11f8b9f8dc29bba`, `compSpeed=0` (generic)
- `0x6d903f6003cca6255d85cca4d3b5e5146dc33925` approves `0xCD18eAa163733Da39c232722cBC4E8940b1D8888` to spend 21213.001006232907484467 COMP (formatted)
- On contract `0xCD18eAa163733Da39c232722cBC4E8940b1D8888`, call `createStream(address recipient, uint256 deposit, address tokenAddress, uint256 startTime, uint256 stopTime)(uint256)` with arguments `recipient=0xd20c9667bf0047f313228f9fe11f8b9f8dc29bba`, `deposit=21213001006232907484467`, `tokenAddress=0xc00e94cb662c3520282e6f5717214004a7f26888`, `startTime=1643184000`, `stopTime=1664265601` (generic)

#### Reports all events emitted from the proposal ✅ Passed
  




Info:
- Events Emitted:
    - Unitroller at `0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B`
        - `ContributorCompSpeedUpdated(contributor: 0xd20c9667bf0047f313228f9fe11f8b9f8dc29bba, newSpeed: 0)`
    - Comp (Compound) at `0xc00e94Cb662C3520282E6f5717214004A7f26888`
        - `Approval(owner: 0x6d903f6003cca6255d85cca4d3b5e5146dc33925, spender: 0xcd18eaa163733da39c232722cbc4e8940b1d8888, amount: 21213001006232907484467)`
        - `Approval(owner: 0x6d903f6003cca6255d85cca4d3b5e5146dc33925, spender: 0xcd18eaa163733da39c232722cbc4e8940b1d8888, amount: 0)`
        - `Transfer(from: 0x6d903f6003cca6255d85cca4d3b5e5146dc33925, to: 0xcd18eaa163733da39c232722cbc4e8940b1d8888, value: 21213001006232907484467)`
    - Sablier at `0xCD18eAa163733Da39c232722cBC4E8940b1D8888`
        - `CreateStream(streamId: 102428, sender: 0x6d903f6003cca6255d85cca4d3b5e5146dc33925, recipient: 0xd20c9667bf0047f313228f9fe11f8b9f8dc29bba, deposit: 21213001006232907484467, tokenAddress: 0xc00e94cb662c3520282e6f5717214004a7f26888, startTime: 1643184000, stopTime: 1664265601)`

#### Check all targets are verified on Etherscan ✅ Passed
  




Info:
- Targets:
    - 0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B: Contract (verified)
    - 0xc00e94Cb662C3520282E6f5717214004A7f26888: Contract (verified)
    - 0xCD18eAa163733Da39c232722cBC4E8940b1D8888: Contract (verified)

#### Check all touched contracts are verified on Etherscan ✅ Passed
  




Info:
- Touched address:
    - 0xDD659911EcBD4458db07Ee7cDdeC79bf8F859AbC: EOA (verification not applicable)
    - 0xc0Da02939E1441F497fd74F78cE7Decb17B66529: Contract (verified)
    - 0x563A63d650a5D259abAE9248dddC6867813d3f87: Contract (verified)
    - 0x6d903f6003cca6255D85CcA4D3B5E5146dC33925: Contract (verified)
    - 0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B: Contract (verified)
    - 0xBafE01ff935C7305907c33BF824352eE5979B526: Contract (verified)
    - 0xc00e94Cb662C3520282E6f5717214004A7f26888: Contract (verified)
    - 0xCD18eAa163733Da39c232722cBC4E8940b1D8888: Contract (verified)

#### Runs solc against the verified contracts ✅ Passed
  




Info:
- Compiler warnings for Sablier at `0xCD18eAa163733Da39c232722cBC4E8940b1D8888`

<details>
<summary>View warnings for Sablier at `0xCD18eAa163733Da39c232722cBC4E8940b1D8888`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>


- Compiler warnings for Unitroller at `0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B`

<details>
<summary>View warnings for Unitroller at `0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>


- Compiler warnings for Comptroller at `0xBafE01ff935C7305907c33BF824352eE5979B526`

<details>
<summary>View warnings for Comptroller at `0xBafE01ff935C7305907c33BF824352eE5979B526`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>


- Compiler warnings for Comp (Compound) at `0xc00e94Cb662C3520282E6f5717214004A7f26888`

<details>
<summary>View warnings for Comp (Compound) at `0xc00e94Cb662C3520282E6f5717214004A7f26888`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>



#### Runs slither against the verified contracts ✅ Passed
  




Info:
- Slither report for Sablier at `0xCD18eAa163733Da39c232722cBC4E8940b1D8888`

<details>
<summary>View report for Sablier at `0xCD18eAa163733Da39c232722cBC4E8940b1D8888`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0xCD18eAa163733Da39c232722cBC4E8940b1D8888
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


- Slither report for Unitroller at `0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B`

<details>
<summary>View report for Unitroller at `0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


- Slither report for Comptroller at `0xBafE01ff935C7305907c33BF824352eE5979B526`

<details>
<summary>View report for Comptroller at `0xBafE01ff935C7305907c33BF824352eE5979B526`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0xBafE01ff935C7305907c33BF824352eE5979B526
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


- Slither report for Comp (Compound) at `0xc00e94Cb662C3520282E6f5717214004A7f26888`

<details>
<summary>View report for Comp (Compound) at `0xc00e94Cb662C3520282E6f5717214004A7f26888`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0xc00e94Cb662C3520282E6f5717214004A7f26888
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


