## Add Market: FEI

_Updated as of block [14749535](https://etherscan.io/block/14749535) at 5/10/2022, 12:07:58 PM ET_

- ID: 83
- Proposer: [0xc8A69971DAa3C3ADd85Ab0d0AF297515769ddfFC](https://etherscan.io/address/0xc8A69971DAa3C3ADd85Ab0d0AF297515769ddfFC)
- Start Block: 14111142 (1/30/2022, 10:09:29 PM ET)
- End Block: 14130852 (2/2/2022, 11:22:46 PM ET)
- Targets: [0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B](https://etherscan.io/address/0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B#code); [0x7713DD9Ca933848F6819F38B8352D9A15EA73F67](https://etherscan.io/address/0x7713DD9Ca933848F6819F38B8352D9A15EA73F67#code)

<details>
  <summary>Proposal text</summary>

> # Add Market: FEI
> Fei USD (FEI) is a highly scalable and decentralized algorithmic stablecoin that utilizes protocol controlled value (PCV) for peg stabilization, while maintaining highly liquid secondary markets. Users can mint FEI from ETH and other bonding curves, while FEI is redeemable at $1 USD (with a 1% fee) for ETH at the peg price.
> 
> FEI is governed by TRIBE holders who manage the PCV, backing FEI with a community-owned reserve.
> 
> This proposal serves to add a market for Fei USD (FEI) with the following parameters:
> - Interest rate model: same as cDAI, cUSDT, and cTUSD (stablecoin standard)
> - Collateral factor: 0% (standard to start)
> - Reserve factor: 25% (standard)
> - Borrow limit: none
> - COMP rewards: none (for now, pending a broader discussion)
> - Price source: Chainlink reporter anchored to [Uniswap V2 FEI/ETH](https://etherscan.io/address/0x94b0a3d511b6ecdb17ebf877278ab030acb0a878)
> 
> References:
> - [Fei Protocol](https://fei.money/)
> - [Etherscan - cFEI](https://etherscan.io/address/0x7713DD9Ca933848F6819F38B8352D9A15EA73F67)
> - [Forums discussion](https://www.comp.xyz/t/add-market-fei/2241/)
> - [Proposal simulation](https://github.com/TylerEther/compound-protocol/blob/add-market-fei/spec/sim/1001-add-market-fei/hypothetical_proposal.sim)
> 
> Proposer disclaimers, affiliations, and transparency:
> - FEI and TRIBE held over the past 90 days: none
> - Compensation for this proposal: none
> - Affiliation to FEI/TRIBE: none
</details>

### Checks
#### Reports all state changes from the proposal ✅ Passed
  




Info:
- State changes:
    - unknown contract name
        - Slot `0x0000000000000000000000000000000000000000000000000000000000000009` changed from `"0x0000000000000000000000000000000000000000000000000000000000c9d668"` to `"0x0000000000000000000000000000000000000000000000000000000000d86297"`
        - Slot `0x0000000000000000000000000000000000000000000000000000000000000008` changed from `"0x0000000000000000000000000000000000000000000000000000000000000000"` to `"0x00000000000000000000000000000000000000000000000003782dace9d90000"`
    - Unitroller at `0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B`
        - Slot `0x6ccf66a3a1e1ee4daa0691bed0c8389e2cbc7d7bb1519237f905a557796f2383` changed from `"0x0000000000000000000000000000000000000000000000000000000000000000"` to `"0x0000000000000000000000000000000000000000000000000000000000000001"`
        - Slot `0x000000000000000000000000000000000000000000000000000000000000000d` changed from `"0x0000000000000000000000000000000000000000000000000000000000000013"` to `"0x0000000000000000000000000000000000000000000000000000000000000014"`
        - Slot `0xd7b6990105719101dabeb77144f2a3385c8033acd3af97e9423a695e81ad1ec8` changed from `"0x0000000000000000000000000000000000000000000000000000000000000000"` to `"0x0000000000000000000000007713dd9ca933848f6819f38b8352d9a15ea73f67"`
        - Slot `0x1898b163e256b2dfbfc6f36f6e7499e1b17a4d6ebd802adcd97b64e4989c5fc9` changed from `"0x0000000000000000000000000000000000000000000000000000000000000000"` to `"0x00d8629700000000000000000000000000c097ce7bc90715b34b9f1000000000"`
        - Slot `0x2fd0526c0ab93b3a320dfaaaace93be38925cdd62f821a50355dba87d9e253f7` changed from `"0x0000000000000000000000000000000000000000000000000000000000000000"` to `"0x00d8629700000000000000000000000000c097ce7bc90715b34b9f1000000000"`

#### Decodes target calldata into a human-readable format ✅ Passed
  




Info:
- On contract `0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B`, call `_supportMarket(address cToken)(uint256)` with arguments `cToken=0x7713dd9ca933848f6819f38b8352d9a15ea73f67` (generic)
- On contract `0x7713DD9Ca933848F6819F38B8352D9A15EA73F67`, call `_setReserveFactor(uint256 newReserveFactorMantissa)(uint256)` with arguments `newReserveFactorMantissa=250000000000000000` (generic)

#### Reports all events emitted from the proposal ✅ Passed
  




Info:
- Events Emitted:
    - Unitroller at `0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B`
        - `MarketListed(cToken: 0x7713dd9ca933848f6819f38b8352d9a15ea73f67)`
    - unknown contract name
        - `AccrueInterest(cashPrior: 0, interestAccumulated: 0, borrowIndex: 1000000000000000000, totalBorrows: 0)`
        - `NewReserveFactor(oldReserveFactorMantissa: 0, newReserveFactorMantissa: 250000000000000000)`

#### Check all targets are verified on Etherscan ✅ Passed
  




Info:
- Targets:
    - 0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B: Contract (verified)
    - 0x7713DD9Ca933848F6819F38B8352D9A15EA73F67: Contract (not verified)

#### Check all touched contracts are verified on Etherscan ✅ Passed
  




Info:
- Touched address:
    - 0xc8A69971DAa3C3ADd85Ab0d0AF297515769ddfFC: EOA (verification not applicable)
    - 0xc0Da02939E1441F497fd74F78cE7Decb17B66529: Contract (verified)
    - 0x563A63d650a5D259abAE9248dddC6867813d3f87: Contract (verified)
    - 0x6d903f6003cca6255D85CcA4D3B5E5146dC33925: Contract (verified)
    - 0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B: Contract (verified)
    - 0xBafE01ff935C7305907c33BF824352eE5979B526: Contract (verified)
    - 0x7713DD9Ca933848F6819F38B8352D9A15EA73F67: Contract (not verified)
    - 0xa035b9e130F2B1AedC733eEFb1C67Ba4c503491F: Contract (verified)
    - 0x956F47F50A910163D8BF957Cf5846D573E7f87CA: Contract (verified)
    - 0xFB564da37B41b2F6B6EDcc3e56FbF523bD9F2012: Contract (verified)

#### Runs solc against the verified contracts ✅ Passed
  




Info:
- Compiler warnings for Fei at `0x956F47F50A910163D8BF957Cf5846D573E7f87CA`

<details>
<summary>View warnings for Fei at `0x956F47F50A910163D8BF957Cf5846D573E7f87CA`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>


- Compiler warnings for Unitroller at `0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B`

<details>
<summary>View warnings for Unitroller at `0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>


- Compiler warnings for Comptroller at `0xBafE01ff935C7305907c33BF824352eE5979B526`

<details>
<summary>View warnings for Comptroller at `0xBafE01ff935C7305907c33BF824352eE5979B526`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>


- Compiler warnings for CErc20Delegate at `0xa035b9e130F2B1AedC733eEFb1C67Ba4c503491F`

<details>
<summary>View warnings for CErc20Delegate at `0xa035b9e130F2B1AedC733eEFb1C67Ba4c503491F`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>


- Compiler warnings for JumpRateModelV2 at `0xFB564da37B41b2F6B6EDcc3e56FbF523bD9F2012`

<details>
<summary>View warnings for JumpRateModelV2 at `0xFB564da37B41b2F6B6EDcc3e56FbF523bD9F2012`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

</details>



#### Runs slither against the verified contracts ✅ Passed
  




Info:
- Slither report for Fei at `0x956F47F50A910163D8BF957Cf5846D573E7f87CA`

<details>
<summary>View report for Fei at `0x956F47F50A910163D8BF957Cf5846D573E7f87CA`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0x956F47F50A910163D8BF957Cf5846D573E7f87CA
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


- Slither report for Unitroller at `0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B`

<details>
<summary>View report for Unitroller at `0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


- Slither report for Comptroller at `0xBafE01ff935C7305907c33BF824352eE5979B526`

<details>
<summary>View report for Comptroller at `0xBafE01ff935C7305907c33BF824352eE5979B526`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0xBafE01ff935C7305907c33BF824352eE5979B526
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


- Slither report for CErc20Delegate at `0xa035b9e130F2B1AedC733eEFb1C67Ba4c503491F`

<details>
<summary>View report for CErc20Delegate at `0xa035b9e130F2B1AedC733eEFb1C67Ba4c503491F`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0xa035b9e130F2B1AedC733eEFb1C67Ba4c503491F
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


- Slither report for JumpRateModelV2 at `0xFB564da37B41b2F6B6EDcc3e56FbF523bD9F2012`

<details>
<summary>View report for JumpRateModelV2 at `0xFB564da37B41b2F6B6EDcc3e56FbF523bD9F2012`</summary>

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
None
Error in 0xFB564da37B41b2F6B6EDcc3e56FbF523bD9F2012
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/crytic_compile/platform/etherscan.py", line 241, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

```

</details>


